services:
  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

  backend:
    build: ./backend
    restart: on-failure
    environment:
      MYSQL_SERVER: mysql
      MYSQL_DATABASE: baza
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8080:8080"

  mysql:
    image: mysql
    container_name: baza
    volumes:
      - mysql-db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: baza
      MYSQL_ROOT_PASSWORD: password

volumes:
  mysql-db: